blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>/<slug:slug>/', views.blog_single, name='blog_single'),
    path('tag/<slug:tag_slug>/', views.blog_index, name='posts_by_tag'),
    path('search/', views.blog_search, name='blog_search'),

]

listings/urls.py
from django.urls import path
from listings import views

app_name = 'listings'


urlpatterns = [
    path('', views.index, name='index'),
    path('listings/', views.listings, name='listings'),
    path('listing/<int:id>/<slug:slug>/', views.single_listing, name='single_listing'),
    path('search/', views.search, name='search'),
    path('add-wishlist/', views.add_wishlist, name='add_wishlist'),
    path('sort/<str:by>', views.sort, name='sort'),
    path('dashboard/properties/marketer/', views.dashboard_marketer_properties, name='dashboard_marketer_properties'),
    path('dashboard/properties/client/', views.dashboard_client_properties, name='dashboard_client_properties'),
    path('dashboard/wishlist/', views.dashboard_wishlist, name='dashboard_wishlist'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('faqs/', views.faqs, name='faqs'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
    path('', include('users.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('blog/', include('blog.urls')),
    path('transactions/', include('transactions.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('s/<str:refer_code>/', views.signup, name='signup'),
    path('activate-email/<str:uid>/<str:token>/', views.activate_email, name='activate_email'),
    path('resend-activation-email/', views.resend_activation_email, name='resend_activation_email'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/client/', views.client_dashboard, name='client_dashboard'),
    path('dashboard/marketer/', views.marketer_dashboard, name='marketer_dashboard'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
]

templates/partials/alerts.html
 {% if messages %}

{% for message  in messages %}

   <div id="message" class="container">
         <div class="alert alert-{{ message.tags }} alert-dimissible text-center" role="alert">
         <button class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span></button>
         {{ message }}
         </div>
   </div>

{% endfor %}

{% endif %}

templates/partials/blog_navbar.html
{% load static %}
{% load custom_tags %}

    <!-- Main navbar -->
    <div class="border-bottom">
        <header class="blog-header container py-2">
            <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1 d-none d-md-block">
                <a class="text-muted p-2" href="{% url 'blog:blog_index' %}">Blog</a>
                <a class="text-muted p-2" href="{% url 'listings:listings' %}">Find Properties</a>
                <a class="text-muted p-2" href="{% url 'listings:index' %}">Back to Westan</a>
            </div>
            <div class="col-4 text-center">
                <a class="navbar-brand" href="{% url 'listings:index' %}">
                    <img src="{% static 'img/logo.svg' %}" alt="Westan Logo" srcset="">
                </a>
            </div>
            
            <div class="col-6 col-md-4 pt-2 d-flex justify-content-end align-items-center rounded">
                <form action="{% url 'blog:blog_search' %}" method="GET">
              <label class="sr-only" for="search">Search</label>
              <div class="input-group mb-2">
                <input type="text" class="form-control border-right-0" id="search" name='q' value='{{ query }}' placeholder="Search" required>
                <div class="input-group-prepend">
                  <button class="input-group-text bg-white border-left-0 rounded" aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-1" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>

                  </button>
                </div>
                </form>
              </div>
            </div>

            </div>
        </header>
    </div>

    <!-- Sliding Navbar -->
    <div class="border-bottom shadow-sm">
        <div class="nav-scroller container py-1 mb-1">
            <nav class="nav d-flex justify-content-betwee align-items-center">
                <span class="nav d-block">

            {# template tag #}
            {% get_tags as all_tags %}

                <!--tagss-->
            {% for tags in all_tags %}

            <a class="p-2 text-muted" href="{% url "blog:posts_by_tag" tags.slug %}">{{ tags.name }}</a>
            
            {% endfor %}
                 </span>
                 
            <span class="text-center ml-auto mt-1 py-md-0">
                <a class="p-2" href="https://web.facebook.com/WestanHomesNG">
                    <img src="{% static 'img/social/facebook.svg' %}" alt="facebook link">
                </a>
                <a class="p-2" href="https://instagram.com/westanhomesng">
                    <img src="{% static 'img/social/instagram.svg' %}" alt="instagram link">
                </a>
                <a class="p-2" href="hhttps://www.linkedin.com/company/westanhomesng/">
                    <img src="{% static 'img/social/linkedin.svg' %}" alt="linkedin link">
                </a>
            </span>
            </nav>
        </div>
    </div>

templates/partials/dashboard_navbar.html
<!-- Navbar -->
{% load static %}
<nav
    class="container navbar navbar-expand-lg fixed-top navbar-light bg-white border-bottom d-block d-md-none box-shadow-sm">
    <a class="navbar-brand" href="{% url 'listings:index' %}">
        <img src="{% static 'img/logo.svg' %}" alt="Westan Logo" srcset="">
    </a>
    <button class="navbar-toggler border-0 float-right pt-3" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto text-center">
           {% if user.is_client %}
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/client' in request.path %} active {% elif 'dashboard/marketer' in request.path %} active {% endif %} " href="{% url 'users:client_dashboard' %}">
                   Client Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}
            {% if user.is_marketer %}
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/client' in request.path %} active {% elif 'dashboard/marketer' in request.path %} active {% endif %} " href="{% url 'users:marketer_dashboard' %}">
                   Marketer Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}
            <li class="nav-item {% if 'dashboard/profile' in request.path %} active {% endif %} ">
                <a class="nav-link" href="{% url 'users:profile' %}">
                    My Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/properties' in request.path %} active {% endif %}"  href="{% if "client" in request.path %} {% url 'listings:dashboard_client_properties' %} {% else %} {% url 'listings:dashboard_marketer_properties' %}  {% endif %} ">
                    Properties
                </a>
            </li>
            <li class="nav-item {% if 'dashboard/wishlist' in request.path %} active {% endif %}">
                <a class="nav-link" href="{% url 'listings:dashboard_wishlist' %}">
                    Wishlist
                </a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">
                    Logout
                </a>
            </li>
        </ul>


    </div>
</nav>

templates/partials/dashboard_search.html
<div class="row mb-4 d-flex align-items-end">
        <h3 class="col font-weight-bold text-center text-md-left mb-4 mb-md-0">Hi {{user.first_name}}</h3>
        
         {% include 'partials/alerts.html' %}

        <div class="col-auto d-none d-md-flex align-items-center">
            <form method="POST" action="{% url 'listings:search' %}">
            {% csrf_token %}
            <label class="sr-only" for="search">Search</label>
            <div class="input-group overflow-hidden rounded border">
                <input type="text" name='q' class="form-control border-0" id="search" placeholder="Search">
                <div class="input-group-prepend">
                    <div class="input-group-text bg-white border-0">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
        </form>
            <a href="{% url 'listings:listings' %}" class="col-auto btn bg-orange text-white px-4 ml-3">Go to Listings</a>
        </div>

    </div>

templates/partials/dashboard_sidebar.html
{% load static %}

<nav id="sidebarMenu" class="sidebar d-print-none col-md-2 d-md-block py-4 px- bg-white shadow-sm border-right collapse">
    <a href="{% url 'listings:index' %}"><img src="{% static 'img/logo.svg' %}" width="100" alt="" class="img-responsive pl-3"></a>

    <div class="sidebar-sticky text-danger pt-5">
        <ul class="nav flex-column">
        {% if user.is_client %}
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/client' in request.path %} active {% endif %} d-flex align-items-center" href="{% url 'users:client_dashboard' %}">
                    <i class="fa fa-th-large mr-2" aria-hidden="true"></i>
                    Client Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}
            {% if user.is_marketer %}
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/marketer' in request.path %} active {% endif %} d-flex align-items-center" href="{% url 'users:marketer_dashboard' %}">
                    <i class="fa fa-th-large mr-2" aria-hidden="true"></i>
                    Marketer Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/profile' in request.path %} active {% endif %} d-flex align-items-center" href="{% url 'users:profile' %}">
                    <i class="fa fa-user mr-2" aria-hidden="true"></i>
                    My Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/properties' in request.path %} active {% endif %}"  href="{% if "client" in request.path %} {% url 'listings:dashboard_client_properties' %} {% else %} {% url 'listings:dashboard_marketer_properties' %}  {% endif %} ">
                    <i class="fa fa-building mr-2" aria-hidden="true"></i>
                    Properties
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if 'dashboard/wishlist' in request.path %} active {% endif %} d-flex align-items-center" href="{% url 'listings:dashboard_wishlist' %}">
                    <i class="fa fa-shopping-bag mr-2" aria-hidden="true"></i>
                    Wishlist
                </a>
            </li>
          
            <li class="nav-item">
                <a class="nav-link d-flex align-items-center" href="{% url 'users:logout' %}">
                    <i class="fa fa-sign-out mr-2" aria-hidden="true"></i>
                    Logout
                </a>
            </li>
        </ul>
    </div>

    <div class="author my-5 py-5 text-cente pl-3 d-none d-md-block">
    {% if user.image %}
        <img src="{{ user.image.url }}" width="100" alt=""
            class="img-responsive rounded-circle border mt-5">
    {% else %}
        <img src="https://ui-avatars.com/api/?name={{user.full_name}}" width="100" alt=""
            class="img-responsive rounded-circle border mt-5">
    {% endif %}        
        <p class="i d-block pt-2">{{ user.full_name }}</p>
    </div>
</nav>

templates/partials/footer.html
<!-- FOOTER -->

{% load static %}
<footer class="pt-4 mt-md-5 pt-md-5">
	<div class="row container mx-auto">
		<div class="col-6 col-md">
			<h5 class="text-uppercase">quick links</h5>
			<ul class="list-unstyled text-small">
				<li><a class="text-muted" href="{% url 'listings:listings' %}">Listings</a></li>
				<li><a class="text-muted" href="#">Featured</a></li>
				<li><a class="text-muted" href="{% url 'listings:contact' %}">Contact</a></li>
				<li><a class="text-muted" href="{% url 'users:signup' %}">Sign Up</a></li>
			</ul>
		</div>
		<div class="col-6 col-md">
			<h5 class="text-uppercase">legal</h5>
			<ul class="list-unstyled text-small">
				<li><a class="text-muted" href="{% url 'listings:privacy' %}">Privacy</a></li>
				<li><a class="text-muted" href="#">Terms & Conditions</a></li>
				<!-- <li><a class="text-muted" href="#">FAQs</a></li> -->
				<li><a class="text-muted" href="#">Money Back Policies</a></li>
			</ul>
		</div>
		<div class="col-6 col-md">
			<h5 class="text-uppercase">others</h5>
			<ul class="list-unstyled text-small">
				<li><a class="text-muted" href="{% url 'listings:faqs' %}">FAQs</a></li>
				<li><a class="text-muted" href="{% url 'blog:blog_index' %}">Blog</a></li>
				<li><a class="text-muted" href="#">Testimonials</a></li>
				<li><a class="text-muted" href="#">About Us</a></li>
			</ul>
		</div>
		<div class="col-6 col-md-5">
			<h5 class="text-uppercase">subscribe</h5>
			<form id="subscribe_form" action='{% url "users:subscribe" %}' method='post'>
				{% csrf_token %}
				<div class="form-md-row align-items-center">
					<div class="my-1">
						<label class="sr-only" for="subscribe">Email</label>
						<input type="email" name="email" class="form-control bg-white" id="subscribe" placeholder="Email address" required>
					</div>
					<div class="w-25 my-1">
						<button type="submit" class="btn btn-primary border-0 text-dark rounded">Submit</button>
					</div>
				</div>
			</form>
			<small class="d-none d-md-block"> Get updates on latest real estate trends

			</small>
		</div>
	</div>

	<hr>
	<div class="container d-flex align-items-center justify-content-between pb-3 py-md-3">
		<small class="d-flex align-items-center">
			<img class="mr-3 brand" src="{% static 'img/logo.svg' %}" alt="">
			&copy; 2020<span class="d-none d-md-block"> Westan Homes. All rights reserved.</span>
		</small>
		<!-- float-right -->
		<p class=" my-auto text-center px-auto py-md-0">
			<a class="px-2" href="https://web.facebook.com/WestanHomesNG">
				<img src="{% static 'img/social/facebook.svg' %}" alt="facebook link">
			</a>
			<a class="px-2" href="https://instagram.com/westanhomesng">
				<img src="{% static 'img/social/instagram.svg' %}" alt="instagram link">
			</a>
			<a class="px-2" href="https://www.linkedin.com/company/westanhomesng/">
				<img src="{% static 'img/social/linkedin.svg' %}" alt="linkedin link">
			</a>
			<a class="px-2" href="https://twitter.com/westanhomesng">
				<img src="{% static 'img/social/twitter.svg' %}" alt="twitter link">
			</a>
			<a class="px-2" href="https://www.youtube.com/channel/UCmjgqpJ-hDDQcZwv8w-znXw/?sub_confirmation=1">
				<img src="{% static 'img/social/youtube.svg' %}" alt="youtube link">
			</a>
		</p>
	</div>
</footer>

templates/partials/navbar.html
{% load static %}

<nav class="px-3 px-lg-5 navbar navbar-expand-lg navbar-light fixed-top bg-white shadow-sm">
    <a class="navbar-brand" href="{% url 'listings:index' %}">
        <img src="{% static 'img/logo.svg' %}" alt="Westan Logo" >
        
    </a>
    <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto text-center">
            <li class="nav-item active">
                <a href="{% url 'listings:index' %}" class="nav-link ml-0 ml-md-3" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link ml-0 ml-md-3" href="{% url 'listings:listings' %}">All Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link ml-0 ml-md-3" href="{% url 'listings:faqs' %}">FAQs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link ml-0 ml-md-3" href="{% url 'blog:blog_index' %}">Blog</a>
            </li>
        </ul>
        <p class="d-block d-md-none my-auto text-center px-auto py-3 py-md-0">
            <a class="px-2" href="https://web.facebook.com/WestanHomesNG">
                <img src="{% static 'img/social/facebook.svg' %}" alt="facebook link">
            </a>
            <a class="px-2" href="https://instagram.com/westanhomesng">
                <img src="{% static 'img/social/instagram.svg' %}" alt="instagram link">
            </a>
            <a class="px-2" href="https://www.linkedin.com/company/westanhomesng/">
                <img src="{% static 'img/social/linkedin.svg' %}" alt="linkedin link">
            </a>
        </p>
        <p class="my-auto text-center px-auto py-3 py-md-0">
        {% if user.is_authenticated %}

               <a href="{% url 'users:dashboard' %}">  
                <button class="btn btn-sm text-md mr-2 py-2 px-5" >
                   <strong>Hi {{user.first_name}}</strong>
                </button> 
                </a>

            <a href="{% url 'users:logout' %}">
                <button class="signup btn btn-sm text-md btn-secondary py-2 px-5" type="submit">
                    <strong>Log Out</strong>
                </button>
            </a>

            {% else %}

            <a href="{% url 'users:login' %}">
                <button class="login btn btn-sm text-md btn-primary mr-2 py-2 px-5" type="submit">
                    <strong>Login</strong>
                </button>
            </a>
            <a href="{% url 'users:signup' %}">
                <button class="signup btn btn-sm text-md btn-secondary py-2 px-5" type="submit">
                    <strong>Sign Up</strong>
                </button>
            </a>
            {% endif %}
        </p>
    </div>
</nav>

templates/partials/pagination.html
<div class="row">
    <div class="col-md-12">

    {% if posts.has_other_pages %}
        <ul class="pagination justify-content-center mt-5">

        {% if posts.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{posts.previous_page_number}}&q={{ request.GET.q }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">&laquo;</a>
            </li>
        {% endif %}

        {% for i in posts.paginator.page_range %}

            {% if posts.number > 3 and forloop.first %}
                
                <li class="page-item disabled">
                <a class="page-link">...</a>
                
                </li>

            {% endif %}

            {% if posts.number == i %}
                <li class="page-item active">
                <a class="page-link">{{i}}</a>
                </li>
            {% elif i > posts.number|add:'-3' and i < posts.number|add:'3' %}
                <li class="page-item ">
                <a class="page-link" href="?page={{i}}&q={{ request.GET.q }}">{{i}}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if posts.paginator.num_pages > posts.number|add:'4' %}
            <li class='page-item'>
            <a class='page-link' href="?page={{ posts.number|add:'5' }}">&hellip;</a>
            </li>
            <li class='page-item'> 
            <a class='page-link' href="?page={{ posts.paginator.count }}">{{ posts.paginator.count }}</a>
            </li>
        {% endif %}

        {% if posts.has_next %}
            <li class="page-item ">
                <a class="page-link" href="?page={{posts.next_page_number}}&q={{ request.GET.q }}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link ">&raquo;</a>
            </li>
        {% endif %}
    {% endif %}

    </div>
</div>