blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>/<slug:slug>/', views.blog_single, name='blog_single'),
    path('tag/<slug:tag_slug>/', views.blog_index, name='posts_by_tag'),
    path('search/', views.blog_search, name='blog_search'),

]

listings/urls.py
from django.urls import path
from listings import views

app_name = 'listings'


urlpatterns = [
    path('', views.index, name='index'),
    path('listings/', views.listings, name='listings'),
    path('listing/<int:id>/<slug:slug>/', views.single_listing, name='single_listing'),
    path('search/', views.search, name='search'),
    path('add-wishlist/', views.add_wishlist, name='add_wishlist'),
    path('sort/<str:by>', views.sort, name='sort'),
    path('dashboard/properties/marketer/', views.dashboard_marketer_properties, name='dashboard_marketer_properties'),
    path('dashboard/properties/client/', views.dashboard_client_properties, name='dashboard_client_properties'),
    path('dashboard/wishlist/', views.dashboard_wishlist, name='dashboard_wishlist'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('faqs/', views.faqs, name='faqs'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
    path('', include('users.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('blog/', include('blog.urls')),
    path('transactions/', include('transactions.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions import views

app_name = 'transactions'

urlpatterns = [
    path("confirm-purchase/<int:listing_id>/", views.confirm_purchase, name="confirm_purchase"),
    path("checkout/<int:trans_id>/", views.checkout, name="checkout"),
    path("checkout-confirmation/<int:trans_id>/", views.checkout_confirmation, name="checkout_confirmation"),
    path("payment-success/<int:listing_id>/", views.payment_success, name="payment_success"),
    path("invoice/<int:listing_id>/", views.invoice, name="invoice"),
]

listings/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from django_google_maps import fields as map_fields

from utils.tools import generate_unique_id
from utils.handlers import image_resizer
from users.models import User



class Listing(models.Model):

    DRAFT, PUBLISHED = 0, 1 
    STATUS_CHOICES = [(DRAFT, 'Draft'), (PUBLISHED, 'Published')]

    HOUSE, LAND = 0, 1 
    TYPE_CHOICES = [(HOUSE, 'House'), (LAND, 'Land')]

    SOLD, AVAILABLE, LEASED = 0, 1, 2
    AVAILABILITY_CHOICES = [(SOLD, 'Sold'), (AVAILABLE, 'Available'), (LEASED, 'Leased')]   
    
    title = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=40)
    state = models.CharField(max_length=40)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField(blank=True, null=True)
    bathrooms = models.IntegerField(blank=True, null=True)
    garage = models.IntegerField(blank=True, null=True)
    area = models.FloatField()
    image = models.ImageField(verbose_name='Main Image', upload_to='listings/img')
    image_1 = models.ImageField(upload_to='listings/img', blank=True, null=True)
    image_2 = models.ImageField(upload_to='listings/img', blank=True, null=True)
    image_3 = models.ImageField(upload_to='listings/img', blank=True, null=True)
    image_4 = models.ImageField(upload_to='listings/img', blank=True, null=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=DRAFT)
    video = models.FileField(upload_to='listings/video', blank=True, null=True)
    vr_image = models.ImageField(upload_to='listings/vr', blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    address = map_fields.AddressField(max_length=200, blank=True, null=True)
    geolocation = map_fields.GeoLocationField(max_length=100, blank=True, null=True)

    # location fileds for maps
    type = models.SmallIntegerField(choices=TYPE_CHOICES, default=HOUSE)
    availability = models.SmallIntegerField(choices=AVAILABILITY_CHOICES, default=AVAILABLE)
    views = models.BigIntegerField(default=0)
    reference = models.CharField(max_length=50, blank=True, null=True)
    featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    
   
    def __str__(self):
        return self.title

    def get_address(self):
        return f'{self.street}, {self.city}, {self.state}'    

    def get_absolute_url(self):
        return reverse("listings:single_listing", args=[self.pk, self.slug])

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)
            self.reference = generate_unique_id(Listing, 'reference', len=10)

        for image in [self.image, self.image_1, self.image_2, self.image_3, self.image_4]:
            if image:
                image_resizer(image)

        super().save(*args, **kwargs)





class WishList(models.Model):
    user = models.ForeignKey(User, models.DO_NOTHING)  
    listing = models.ForeignKey(Listing, models.DO_NOTHING)  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.listing}'
    

listings/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget
from django_google_maps.widgets import GoogleMapsAddressWidget

from listings.models import Listing



class ListingAdminForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Listing
        fields = '__all__'



class ListingMapForm(forms.ModelForm):

    class Meta(object):
        model = Listing
        fields = ['address', 'geolocation']
        widgets = {
            "address": GoogleMapsAddressWidget,
        }

listings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
from django.urls import reverse

from listings.models import Listing, WishList
from transactions.models import Transaction
from listings.forms import ListingMapForm
from utils.handlers import send_contact_us_mail


def index(request):  #home page
    return render(request, 'listings/home.html')


def listings(request):

    queryset = Listing.objects.filter(status=Listing.PUBLISHED).order_by('-created_at')

    paginator = Paginator(queryset, 3) # 3 posts per page
    page = request.GET.get('page')
    try:
        listings = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an intger deliver the first page
        listings = paginator.page(1)
    except EmptyPage:
        #  if page is out of range deliver last page of results
        listings = paginator.page(paginator.num_pages)
   
    context = {
        'listings': listings
    }

    return render(request, 'listings/all_listings.html', context)


def single_listing(request, id, slug):
    wish = False
    form = ListingMapForm()

    listing = get_object_or_404(Listing, id=id)
    listing.views += 1
    listing.save()

    if request.user.is_authenticated:
        try:
            wish = WishList.objects.get(user=request.user, listing=listing)
            wish = True 
        except Exception as e:
            pass

    context = {
        'listing' : listing, 'wish': wish, 'form': form,
    }
    return render(request, 'listings/single_listings.html', context)


def add_wishlist(request):
    final_status, auth = None, None

    if request.user.is_authenticated:

        listing_id = request.GET.get('listing_id')

        wish = WishList.objects.filter(listing_id=listing_id, user=request.user)

        if wish.exists():
            wish.delete()
            final_status = False

        else:
            WishList.objects.create(user=request.user, listing_id=listing_id)
            final_status = True

    else:
        auth = """
        Please login to add this listing to your wish list: <br/> <br/> <a href='/login/'> Click to Login </a>  
        """

    data = {'final_status': final_status, 'auth': auth}

    return JsonResponse(data)


def search(request):
    results = []

    query = request.GET['q'] if 'q' in request.GET else None
    type = request.GET['type'] if 'type' in request.GET else None
    bedrooms = request.GET['bedrooms'] if 'bedrooms' in request.GET else None
    bathrooms = request.GET['bathrooms'] if 'bathrooms' in request.GET else None
    reference = request.GET['reference'] if 'reference' in request.GET else None
    minprice = request.GET['minprice'] if 'minprice' in request.GET else None
    maxprice = request.GET['maxprice'] if 'maxprice' in request.GET else None


    queryset = Listing.objects.filter(status=Listing.PUBLISHED)

    if type:
        queryset = queryset.filter(type__iexact=type)

    if query:
        queryset = queryset.filter(title__icontains=query)

    if bedrooms:
        queryset = queryset.filter(bedrooms__lte=bedrooms)

    if bathrooms:
        queryset = queryset.filter(bathrooms__lte=bathrooms)

    if maxprice:
        queryset = queryset.filter(price__lte=maxprice)    

    if minprice:
        queryset = queryset.filter(price__gte=minprice)    

    if reference:
        queryset = Listing.objects.filter(reference=reference)

    paginator = Paginator(queryset, 1) # 3 posts per page
    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an intger deliver the first page
        results = paginator.page(1)
    except EmptyPage:
        #  if page is out of range deliver last page of results
        results = paginator.page(paginator.num_pages)

    
    context = {
        'listings': results,
        'values': request.GET
    }
    return render(request, 'listings/search_listings.html', context) 


def sort(request, by=None):
    queryset = None

    if by == 'maxprice':
        queryset = Listing.objects.filter(status=Listing.PUBLISHED).order_by('-price')

    if by == 'minprice':
        queryset = Listing.objects.filter(status=Listing.PUBLISHED).order_by('price')

    if by == 'latest':
        queryset = Listing.objects.filter(status=Listing.PUBLISHED).order_by('-created_at')

    if by == 'popular':
        queryset = Listing.objects.filter(status=Listing.PUBLISHED).order_by('-views')

    paginator = Paginator(queryset, 3) # 3 posts per page
    page = request.GET.get('page')
    try:
        listings = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an intger deliver the first page
        listings = paginator.page(1)
    except EmptyPage:
        #  if page is out of range deliver last page of results
        listings = paginator.page(paginator.num_pages)
   
    context = {
        'listings': listings
    }
    return render(request, 'listings/all_listings.html', context)


def dashboard_marketer_properties(request):
    referred_users_ids = [user.id for user in request.user.referrals.all()]
    trans = Transaction.objects.filter(user_id__in=referred_users_ids)

    return render(request, 'listings/dashboard_marketer_properties.html', {"trans": trans})


def dashboard_client_properties(request):
    trans = Transaction.objects.filter(user=request.user, status__in=[Transaction.ALLOCATED, Transaction.COMPLETED, Transaction.RECEIVED])
    context = {
        'trans': trans 
        }
    return render(request, 'listings/dashboard_client_properties.html', context)


def dashboard_wishlist(request):
    wishes = WishList.objects.filter(user=request.user)
    return render(request, 'listings/dashboard_wishlist.html', {'wishes': wishes}) 


def contact(request):
    if request.method == "POST":
        send_contact_us_mail(request.POST)

        data = {'success': 'Hang on! We will get back to you!'}
        return JsonResponse(data)    
    return render(request, 'listings/contact.html')


def privacy(request):
    return render(request, 'listings/privacy.html') 


def faqs(request):
    return render(request, 'listings/faqs.html')    

templates/listings/all_listings.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}


{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

<style>
      .masthead h1 {
        max-width: 850px;
      }
      .modal .modal-content {
        background-color: #F9FEFF !important;
        border: 0;
      }
      .modal {
        padding: 0 !important;
      }
      .modal .modal-body form select {
        background-color: #ffffff !important;
        border-color: #73738d88 !important;
      }
      .apply-filters {
        background-color: #FFF200 !important;
        color: black !important;
        font-weight: bold;
      }
      .clear-filters {
        background-color: black !important;
        color: white !important;
      }
    </style>
</style>
{% endblock extrastyle %}

{% block title %} All Listings {% endblock title %}




{% block content %}

<!-- Dont remove this-->
<header class=""> 


{% include 'partials/navbar.html' %}

      <!-- Hero -->
          <section class="masthead container">
            <div class="col-md-12">
                <h1 class="col-md-12 mt-5 mt-md-0 mb-5 mx-auto text-center text-uppercase">
                  <strong>
                    search for GREAT properties AT AMAZING PRICES
                  </strong>
                </h1>
              <div class="col-md-12 col-lg-9 mx-auto mb-5">
                <form action="{% url 'listings:search' %}" method='GET'>
                  <div class="form-row">
                    <div class="col-12 col-md-6 mb-2 mb-md-0 py-2" style="background-color: #EBF5F7;" >
                      <input type="text" name='q'  class="form-control form-control-lg bg-transparent border-0 pl-4 py-2" placeholder="Search property locations...">
                    </div>
    
                    <div class="col-12 col-md-3 mb-2 mb-md-0 py-2 border-left" style="background-color: #EBF5F7;">
                      <select name='type' class="custom-select custom-select-lg bg-transparent border-0" placeholder="Enter your email...">
                        <option value="">Select Type</option>
                        <option value="0">House</option>
							          <option value="1">Land</option>
                      </select>
                    </div>
                    <div class="col-12 col-md-3">
                      <button type="submit" class="btn btn-block btn-lg w-100 py-3">Search</button>
                    </div>
                  </div>
                </form>

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-light mt-3 " data-toggle="modal" data-target="#exampleModal">
                  <img src="{% static 'img/filter.svg' %}" alt="instagram link" class="mr-2">Additional Filters
                </button>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-body bg-light rounded-lg">
                        <form class="p-5" action="{% url 'listings:search' %}" method='GET'>
                          <p class="text-center h4 mb-3 mb-md-5"><strong>Filters</strong> </p>
                          
                            <div class="form-row">
                           
                              <div class="col-md-6 mb-4">
                                 <label for="noBathrooms">Search property locations</label>
                                <input class="form-control bg-white" name='q' type="text" value='{{ values.q }}' placeholder="Search property locations" aria-label="Search">
                              </div>

                              <div class="col-md-6 mb-3">
                                <label for="noRooms">Type</label>
                                <select name='type' class="custom-select" id="noRooms">
                                  <option value="0">House</option>
                                  <option value="1">Land</option>
                                </select>
                              </div>
                            </div>
                            <div class="form-row">
                            
                               <div class="col-md-6 mb-4">
                                <label for="noBathrooms">Number of Bedrooms</label>
                                <select name='bedrooms' class="custom-select" id="noBathrooms">
                                  <option value="0" disabled selected>Number of Bedrooms</option>
                                  <option value="1">1</option>
                                  <option value="2">2</option>
                                  <option value="3">3</option>
                                  <option value="4">4</option>
                                  <option value="5">5</option>
                                  <option value="6">6+</option>
                                </select>
                              </div>
                              
                              <div class="col-md-6 mb-3">
                                <label for="noBathrooms">Number of Bathrooms</label>
                                <select name='bathrooms' class="custom-select" id="noBathrooms">
                                  <option value="0" disabled selected>Number of Bathrooms</option>
                                  <option value="1">1</option>
                                  <option value="2">2</option>
                                  <option value="3">3</option>
                                  <option value="4">4</option>
                                  <option value="5">5</option>
                                  <option value="6">6+</option>
                                </select>
                              </div>
                            </div>
                            <div class="form-row">
                              
                              <div class="col-md-3 mb-3">
                                <label for="maxPrice">Price</label>
                                <select name='maxprice' class="custom-select" id="maxPrice">
                                  <option value="0" disabled selected>Max Price</option>
                                  <option value="100000">100,000</option>
                                  <option value="250000">250,000</option>
                                  <option value="500000">500,000</option>
                                  <option value="750000">750,000</option>
                                  <option value="1000000">1 million</option>
                                  <option value="2000000">2 million</option>
                                  <option value="5000000">5 million</option>
                                  <option value="10000000">10 million</option>
                                  <option value="20000000">20 million+</option>
                                </select>
                              </div>
                              <div class="col-md-3 mb-3">
                                <label for="minPrice" class="text-light">State</label>
                                <select name='minprice' class="custom-select" id="minPrice">
                                  <option value="0" disabled selected>Min Price</option>
                                  <option value="100000">100,000</option>
                                  <option value="250000">250,000</option>
                                  <option value="500000">500,000</option>
                                  <option value="750000">750,000</option>
                                  <option value="1000000">1 million</option>
                                  <option value="2000000">2 million</option>
                                  <option value="5000000">5 million</option>
                                  <option value="10000000">10 million</option>
                                  <option value="20000000">20 million+</option>
                                </select>
                              </div> 

                              <div class="col-md-6 mb-4">
                                 <label for="reference">Property Reference</label>
                                <input class="form-control bg-white" name='reference' type="text" placeholder="Get exact property with reference" aria-label="Reference">
                              </div>

                            </div>
                            
                            <div class="form-row">
                              <div class="col-md-6 mb-3">
                                <button class="clear-filters btn btn-primary border-0 rounded w-100" type="button" data-dismiss="modal">Close Filters</button>
                              </div>
                              <div class="col-md-6 mb-3">
                                <button class="apply-filters btn btn-primary border-0 rounded w-100" type="submit">Apply Filters</button>
                              </div>
                              
                            </div>
                          </form>
                          
                            

                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </section>

    </header>


    
    <!-- Sorting -->
    <main class=" py-5">
      <div class="container">
        <dix class="mb-3 d-flex justify-content-between align-items-center">
          <span class="h4 text-uppercase">All listings</span>
          <span class="">
            <span class="mr-2">Sort By</span>
            <div class="btn-group">
              <button type="button" class="btn btn-muted border border-secondary btn-sm dropdown-toggle mr-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if 'sort/latest' in request.path %} Latest {% elif 'sort/popular' in request.path %} Popular {% else %}  Popularity {% endif %}
              </button>
              <div class="dropdown-menu dropdown-menu-right">
              <a href="{% url 'listings:sort' 'latest' %}"><button class="dropdown-item" type="button">Latest</button></a>
              <a href="{% url 'listings:sort' 'popular' %}"> <button class="dropdown-item" type="button">Popular</button></a>
              </div>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-muted border border-secondary btn-sm dropdown-toggle mr-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if 'sort/maxprice' in request.path %} Max Price {% elif 'sort/minprice' in request.path %} Min Price {% else %}  Price {% endif %}
              </button>
              <div class="dropdown-menu dropdown-menu-right">
              <a href="{% url 'listings:sort' 'maxprice' %}"><button class="dropdown-item" type="button">Max Price</button></a>
              <a href="{% url 'listings:sort' 'minprice' %}"> <button class="dropdown-item" type="button">Min Price</button></a>
              </div>
            </div>
          
          </span>
        </dix>


     <!-- Listings -->
        <div class="row">
          
          
        {% for listing in listings %}

          <div class="col-md-4 py-3">
            <div class="card shadow-sm bg-white text-dark text-white" style="min-width: 18rem;">
              <img class="card-img" src="{{ listing.image.url }}" alt="Card image">
              <div class="card-img-overlay d-flex justify-content-between">
                <p></p>
                <h5 class="price rounded text-white"><span>&#8358;</span>{{listing.price|intcomma}}</h5>
              </div>
              <div class="card-body">
                <h4 class="card-title"><strong><a href="{{ listing.get_absolute_url }}" class="stretched-link"></a>{{ listing.title }}</strong></h4>
                <p class="card-text">{{ listing.get_address }}.</p>
              </div>
              <div class="card-footer">
                <small class="text-muted mb-0 d-flex justify-content-between">
                  <span>{{ listing.bedrooms }} Rooms</span>
                  <span>{{ listing.bathrooms }} Baths</span>
                  <span>{{ listing.garage }} Parking spaces</span>
                  <span>{{ listing.area}}m<sup>2</sup></span>
                </small>
              </div>
            </div>
          </div>
          {% empty %}

          <h3>No Listings Yet</h3>

          {% endfor %}

        </div>      <!-- Listings end-->


        <!-- Pagination -->
        {% include 'partials/pagination.html' with posts=listings %}

        
      </div>
    </main>
    <!-- Listings end -->

    
 
{% include 'partials/footer.html' %}


{% endblock content %}

templates/listings/contact.html
{% extends 'base.html' %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/aos.css' %}">
<style>
.signup {
    background-color: #FFF200;
    color: black;
    border: 0;
}
.login {
    background-color: black;
    color: white;
    border: 0;
}
form button {
    font-size: 1rem !important;
    background-color: #FFF200 !important;
}
.signup:hover, .login:hover {
    background-color: white;
    border: 1px solid black;
    color: black;
}

</style>
{% endblock extrastyle %}

{% block title %} Contact Us {% endblock title %}


{% block content %}

<div class="container-fluid main-view">

   {% include 'partials/navbar.html' %}
   {% include 'partials/alerts.html' %}


   <!-- =================== Hero PAge ========================= -->


   <div class="row" style="margin-bottom: 15%">
    <div class="col-12 section-1">
       <h1 class="headliner">Contact Us</h1>
       <p class="headliner-summary">We’re here to help and answer any question you might have. <br> We look forward to hearing from you 🙂</p>
    </div>
    <br>
    <div class="col-6 offset-3" style="text-align:center;">
    <br>
       <button type="button" class="hero-btn btn btn-primary" onclick="window.location='#contactform';">GET IN TOUCH</button>
    </div>
 </div>
</div>
 
<br> <br> 



        <section id="contactform">
          <div class="container">
              <div class="row">
                  <div class="col-lg-8 col-sm-10 p-5 shadow rounded-lg mx-auto" data-aos="zoom-in" data-aos-duration="800">
                      <h5 style=" text-align:center;">WE WILL LOVE TO HEAR FROM YOU</h5>
                      <hr>
                      <br>
                      <br>

                        <form id="form" action='{% url 'listings:contact' %}' method="POST" >
                        {% csrf_token %}
                            <div class="form-group">
                                <label for="Fullname"><span class="comp">*</span> Full Name</label>
                                <input type="text" class="form-control scnd_form" id="fullname" name="fullname" required >
                                </div>
                                <br> 

                                <div class="form-group">
                                    <label for="email"><span class="comp">*</span> Email</label>
                                    <input type="email" class="form-control scnd_form" name="email" required >
                                </div>
                                <br>
                            
                                  <div class="form-group">
                                    <label for="number"><span class="comp">*</span> Phone Number</label>
                                    <input type="text" class="form-control scnd_form" name="phone" required >
                                </div>
              
                                <br>
                                
                                    <div class="form-group">
                                      <label for="msg">Your Message</label>
                                      <!-- <input type="text" class="form-control scnd_form"  name="message"> -->
                                      <textarea class="form-control scnd_form" name="message" id="" cols="30" rows="3"></textarea>
        
                                    </div>
                            
                                
                                <div class="text-center mt-5">
                                    <button id="my-form-button" type="submit" class="btn pr-5 pl-5 font-weight-bold" >
                                        SUBMIT
                                    </button>
                                </div>
                            </form>

                        
                        </div>
                        
                    </div>
                </div>
                <br><br>
            </section>
<br>
<br>
 <br>
 <br>

{% include 'partials/footer.html' %}


{% endblock content %}


{% block javascript %}
<script src="{% static 'js/aos.js' %}"></script>
<script>
    AOS.init();
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
$(document).on('submit', '#form', function(e){
    var form = $(this);
 
        $.ajax({
            url: '{% url 'listings:contact' %}',
            data: form.serialize(),
            type: 'post',
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    swal({
                        title: "Message Delivered!",
                        text: data.success,
                        icon: "success",
                        button: "Done!",
                    });

                    document.getElementById("form").reset();
                }
        }

    })
    return false;

    });
    </script>
{% endblock javascript %}