blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>/<slug:slug>/', views.blog_single, name='blog_single'),
    path('tag/<slug:tag_slug>/', views.blog_index, name='posts_by_tag'),
    path('search/', views.blog_search, name='blog_search'),

]

listings/urls.py
from django.urls import path
from listings import views

app_name = 'listings'


urlpatterns = [
    path('', views.index, name='index'),
    path('listings/', views.listings, name='listings'),
    path('listing/<int:id>/<slug:slug>/', views.single_listing, name='single_listing'),
    path('search/', views.search, name='search'),
    path('add-wishlist/', views.add_wishlist, name='add_wishlist'),
    path('sort/<str:by>', views.sort, name='sort'),
    path('dashboard/properties/marketer/', views.dashboard_marketer_properties, name='dashboard_marketer_properties'),
    path('dashboard/properties/client/', views.dashboard_client_properties, name='dashboard_client_properties'),
    path('dashboard/wishlist/', views.dashboard_wishlist, name='dashboard_wishlist'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('faqs/', views.faqs, name='faqs'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
    path('', include('users.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('blog/', include('blog.urls')),
    path('transactions/', include('transactions.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions import views

app_name = 'transactions'

urlpatterns = [
    path("confirm-purchase/<int:listing_id>/", views.confirm_purchase, name="confirm_purchase"),
    path("checkout/<int:trans_id>/", views.checkout, name="checkout"),
    path("checkout-confirmation/<int:trans_id>/", views.checkout_confirmation, name="checkout_confirmation"),
    path("payment-success/<int:listing_id>/", views.payment_success, name="payment_success"),
    path("invoice/<int:listing_id>/", views.invoice, name="invoice"),
]

users/urls.py
from django.urls import path

from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('s/<str:refer_code>/', views.signup, name='signup'),
    path('activate-email/<str:uid>/<str:token>/', views.activate_email, name='activate_email'),
    path('resend-activation-email/', views.resend_activation_email, name='resend_activation_email'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/client/', views.client_dashboard, name='client_dashboard'),
    path('dashboard/marketer/', views.marketer_dashboard, name='marketer_dashboard'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from taggit.managers import TaggableManager

from users.models import User
from utils.handlers import image_resizer


class Post(models.Model):

    DRAFT, PUBLISHED = 0, 1
    status_choices = ((DRAFT, 'Draft'),
                    (PUBLISHED, 'Published'))

    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=250, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.SmallIntegerField(default=DRAFT, choices=status_choices)
    image = models.ImageField(upload_to='blog', null=True)  
    views = models.BigIntegerField(default=0)  
    featured = models.BooleanField(default=False, help_text='Whether post should appear on slide')                        

    tags = TaggableManager()                                                  

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog_single", args=[self.pk, self.slug])

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)

        if self.image:    
            image_resizer(self.image)
            
        super().save(*args, **kwargs)

                                                                    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from utils.tools import generate_unique_id
from users.managers import CustomUserManager
from utils.handlers import image_resizer


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='email address', unique=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    email_verified = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    is_marketer = models.BooleanField(default=False)
    refer_code = models.CharField(
        max_length=15,
        unique=True,
        editable=False,
    )
    referer = models.ForeignKey(
        'self', 
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='referrals'
    )
    next_of_kin = models.CharField(max_length=50, null=True, blank=True)
    send_notifications = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='users', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return "{} {} - {}".format(self.first_name, self.last_name, self.email)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.refer_code = generate_unique_id(User, 'refer_code')

        if self.image: 
            image_resizer(self.image)    

        super(User, self).save(*args, **kwargs)


class Subscribe(models.Model):

    email = models.EmailField(max_length=100)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        verbose_name_plural = "Subscribers"

    def __str__(self):
        return self.email

users/views.py
from datetime import timedelta

from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator  
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.db.models import Sum

from users.models import User, Subscribe
from utils.handlers import send_activation_email
from transactions.models import Transaction
from listings.models import Listing


def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        next = request.POST.get('next')

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)

            user_type = request.POST.get('user_type')

            if user_type == 'client' and user.is_client:
                messages.success(request, 'You are now logged in, as a client')
                if next:
                    return redirect(next)
                return redirect(reverse('users:client_dashboard')) # client dashboard

            elif user_type == 'marketer' and user.is_marketer:
                messages.success(request, 'You are now logged in, as a marketer')
                if next:
                    return redirect(next)
                return redirect(reverse('users:marketer_dashboard')) # marketer dashboard

            else:
                auth.logout(request) #log user out
                messages.success(request, 'You are neither a client or a marketer')
                return redirect(reverse('listings:index')) # home

        else:
            messages.error(request, 'Invalid credentials')
            return render(request, 'users/login.html', {'email': email})

    return render(request, 'users/login.html')


def signup(request, refer_code=None):

    if refer_code:
        request.session['refer_code'] = refer_code.lower()

    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        referer = None

        if User.objects.filter(email=email).exists():
            messages.error(request, 'This email is in use')
            return render(request, 'users/signup.html', {'email': email,
                                            'first_name': first_name,
                                            'last_name': last_name,
                                            'phone': phone })

        if request.session.get('refer_code'):
            try:
                referer = User.objects.get(refer_code=request.session['refer_code'])
            except:
                pass

        user_type = request.POST.get('user_type')

        if user_type == 'client': 

            user = User.objects.create_user(first_name=first_name,
                                            last_name=last_name,
                                            email=email, 
                                            phone=phone,
                                            referer=referer,
                                            is_client=True,
                                            password=password)

        elif user_type == 'marketer': 

            user = User.objects.create_user(first_name=first_name,
                                            last_name=last_name,
                                            email=email, 
                                            phone=phone,
                                            referer=referer,
                                            is_marketer=True,
                                            password=password)
        else:
            messages.error(request, 'Must be a client or marketer')
            return render(request, 'users/signup.html')

        send_activation_email(request, user)
        messages.success(request, 'Registeration successful! Kindly verify your email and login')
        return redirect(reverse('users:login'))

    return render(request, 'users/signup.html')


def logout(request):
    auth.logout(request)
    messages.info(request, "You're now logged out")
    return redirect('listings:index')


@login_required
def dashboard(request):
    if request.user.is_client:
        return redirect(reverse('users:client_dashboard'))

    elif request.user.is_marketer:    
        return redirect(reverse('users:marketer_dashboard'))
        
    else:
        return redirect(reverse('listings:index'))    


@login_required
def client_dashboard(request):
    if request.user.is_client:
        context = {}
        transactions = Transaction.objects.filter(user=request.user) #get user specific trans
        allocated_properties = transactions.filter(status=Transaction.ALLOCATED) # allocated ppties

        # incomplete transactions
        incomplete_transactions = transactions.exclude(status__in=[Transaction.ALLOCATED, Transaction.COMPLETED])
        # get last incomplete trans, and the it's listing
        last_incomplete_tran = incomplete_transactions.last() 

        if last_incomplete_tran:
            last_listing = last_incomplete_tran.listing

            # sum of all the amounts paid
            sum_paid = incomplete_transactions.filter(listing=last_listing).aggregate(Sum('amount_paid'))['amount_paid__sum']
            
            # listing price
            listing_price = last_incomplete_tran.listing.price        
            
            pending_payment = listing_price - sum_paid
            payment_progress = round(((sum_paid / listing_price) * 100), 2)

            context['pending_payment'] = pending_payment
            context['sum_paid'] = sum_paid
            context['payment_progress'] = payment_progress

        context['allocated_properties'] = allocated_properties
        context['transactions'] = transactions
        context['incomplete_trans'] = last_incomplete_tran

        return render(request, 'users/client.html', context)

    return redirect(reverse('listings:index'))    


@login_required
def marketer_dashboard(request):
    COMMISSION = 0.07  # 10% percent commission earned
    if request.user.is_marketer:
        referrals = request.user.referrals.all()
        trending_listings = Listing.objects.filter(status=Listing.PUBLISHED).order_by('-views')[:10]
        referred_users_ids = [user.id for user in referrals]
        # trans = Transaction.objects.filter(user_id__in=referred_users_ids).distinct("listing") # works only with postgres
        trans = Transaction.objects.filter(user_id__in=referred_users_ids)
        total_sales = trans.filter(status__in=[Transaction.ALLOCATED, Transaction.COMPLETED]).aggregate(Sum('amount_paid'))['amount_paid__sum'] or 0.0
        commission_earned = total_sales * COMMISSION

        sales_data = []
        now = timezone.now()

        counter = 1
        while counter < 13:
            counter += 1

            month = now - timedelta(days=counter*30)

            sales_data.append(trans.filter(created_at__month=month.month).aggregate(Sum('amount_paid'))['amount_paid__sum'] or 0.0)


        context = {
            "referrals": referrals,
            "trending_listings": trending_listings,
            "num_properties": trans.count(),
            "total_sales": total_sales,
            "commission_earned": commission_earned,
            "sales_data": sales_data,
        }
        return render(request, 'users/marketer.html', context)
        
    return redirect(reverse('listings:index'))    



@login_required
def resend_activation_email(request):
    '''To resend activation email to a user'''
    
    send_activation_email(request, request.user)
    messages.info(request, f'Verification email sent to {request.user.email}')
    return redirect('listings:index')


def activate_email(request, uid, token):
    '''To activate the email address'''
    try:
        id = force_text(urlsafe_base64_decode(uid))
        user = User.objects.get(id=id)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    context = {}

    if user and user.email_verified:
        context['message'] = 'Your email has already been verified'
        # return render(request, 'account_activation.html', context)
        return HttpResponse('Your email has already been verified')

    if user and default_token_generator.check_token(user, token):

        user.email_verified = True
        user.save()

        context['message'] = 'Email verification successful'
        # return render(request, 'account_activation.html', context)
        return HttpResponse('Email verification successful')

    else:
        context['message'] = 'Email verification failed'
        # return render(request, 'account_activation.html', context)
        return HttpResponse('Email verification failed')



def profile(request):
    return render(request, 'users/profile.html')


def edit_profile(request, user_id):

    if request.method == 'POST':
        user = get_object_or_404(User, id=user_id)

        image = request.FILES.get('image')
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.phone = request.POST.get('phone')
        user.address = request.POST.get('address')
        user.next_of_kin = request.POST.get('next_of_kin')
        user.send_notifications = True if request.POST.get('send_notifications') else False

        if image:
            fs = FileSystemStorage()
            fs.save(image.name, image)
            user.image = image

templates/users/client.html
{% extends 'base.html' %}

{% load static humanize %}

{% load custom_tags %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    .pie-img {
        margin-top: -175px !important;
    }
    .pie-img .fa {
        font-size: 20px;
    }
</style>
{% endblock extrastyle %}

{% block title %} Client Dashboard {% endblock title %}




{% block content %}


<body class="container-fluid">
    <div class="header">
        {% include 'partials/dashboard_navbar.html' %}
    </div>
    <div class="row">
    
        <!-- Sidebar -->
        {% include 'partials/dashboard_sidebar.html' %}
        <!-- Sidebar ends -->


        <!-- Main content -->
        <main role="main" class="col-md h-100 overflow-aut p-4">
            <div class="py-5 d-block d-md-none"></div>

            <!-- Heading and Filters -->

            {% include 'partials/dashboard_search.html' %}

            <!-- Cards -->
            <div class="row">

            {% if incomplete_trans.listing %}
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm mb-4 widget-flat overflow-hidden">
                        <div class="card-body text-center">
                            <img src="{% static 'img/desc-images/easy.png' %}" class="rounded img-responsive w-50" alt="">
                            <span class=" d-block">
                                <p class="grey my-2">Ongoing Purchases</p>
                                <p class="h5 md-h6 font-weight-bold">{{ incomplete_trans.listing.title }}</p>
                            </span>
                        </div> 
                        <!-- card footer-->
                        <div class="card-footer border-top bg-white d-flex justify-content-around">
                            <span class="text-center d-block">
                                <p class="h5 font-weight-bold pb-0 mb-0">{{incomplete_trans.listing.price|shrink}}</p>
                                <p class="grey">Total Cost</p>
                            </span>
                            <div class="bg-grey rounded mt-1" style="width: 1px; height: 36px;"></div>
                            <span class="text-center d-block">
                                <p class="h5 font-weight-bold pb-0 mb-0">{{sum_paid|shrink}}</p>
                                <p class="grey">Amount Paid</p>
                            </span>
                            <div class="bg-grey rounded mt-1" style="width: 1px; height: 36px;"></div>
                            <span class="text-center d-block">
                                <p class="h5 font-weight-bold pb-0 mb-0">{{pending_payment|shrink}}</p>
                                <p class="grey">Amount Due</p>
                            </span>
                        </div>
                    </div> <!-- end card-->
                </div>

                <div class="col-md-4">
                    <div class="card border-0 shadow-sm mb-4 widget-flat">
                        <div class="card-body">
                            <div class="position-relative d-block">
                                <div class="mx-auto w-75">
                                    <canvas class="" id="chartCanvas" width="165" height="165" aria-label="Payment Progress" role="img"></canvas>
                                
                                </div>
                                <div class="pie-img position-absolute text-center w-100 mb-5">
                                    <i class="fa fa-credit-card p-4 rounded-circle orange bg-light-red" aria-hidden="true"></i>
                                    <p class="h2 font-weight-bold pb-0 mb-0">{{payment_progress}}%</p>
                                    <p class="grey">Payment Progress</p>
                                </div>
                                
                            </div>
                        </div>
                        <!-- card footer-->
                        <div class="card-footer mt-1 border-top bg-white d-flex justify-content-around">
                            <span class="text-center d-block">
                                <p class="grey pb-0 mb-0">Pending Payment</p>
                                <p class="h5 font-weight-bold"><span>&#8358;</span>{{pending_payment|intcomma}}</p>
                                
                            </span>
                            <div class="bg-grey rounded mt-1" style="width: 1px; height: 36px;"></div>
                            <span class="text-center d-block pt-1">
                                <a href="{% url 'transactions:checkout' incomplete_trans.id %}" class="col-auto btn bg-orange text-white px-4 ml-3 {% if sum_paid|add:"1" >= incomplete_trans.listing.price %} disabled {% endif %} ">Pay Now</a>
                            </span>
                            
                        </div>
                    </div> <!-- end card-->
                </div>

                {% endif %}
                
                <!-- Transactions -->
                <div class="col-md-4">
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-body">
                            <h5 class="font-weight-bold mt-2">Transactions</h5>

                            <div class="table-responsive">
                                <table class="table table-centered nowrap table-hover mb-0 dtr-inline collapsed">
                                    <thead>
                                        <tr class="border-top border-bottom">
                                            <th class="text-muted border-0 py-2 font-weight-normal">Property</th>
                                            <th class="text-muted border-0 py-2 font-weight-normal">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for trans in transactions %}
                                        <tr>
                                            <td class="border-0">
                                                <img src="{{trans.listing.image.url}}"
                                                    class="rounded-circle img-responsive mr-2" height="30" width="30"
                                                    alt="">
                                                {{trans.listing.title}}
                                            </td>
                                            <td class="border-0 pt-3 {% if trans.get_status_display in 'Allocated, Complete' %} green {% elif  trans.get_status_display in 'Processing, Received' %} blue {% else %} red {% endif %} ">
                                                {{trans.get_status_display}}
                                            </td>
                                        </tr>
                                        {% empty %}

                                        <tr>
                                            <br>
                                            <td>  No transactions </td>
                                        </tr>

                                        {% endfor %}
                                        

                                    </tbody>
                                </table>
                            </div> <!-- end table-responsive-->
                        </div> <!-- end card-body-->
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card border-0 shadow-sm mb-4">
                        <div class="card-body">
                            <h5 class="font-weight-bold mt-2">Allocated Properties</h5>

                            <div class="table-responsive">
                                <table class="table table-centered nowrap table-hover mb-0 dtr-inline collapsed">
                                    <thead>
                                        <tr class="border-top border-bottom">
                                            <th class="text-muted border-0 py-2 order-0 font-weight-normal">Property
                                            </th>
                                            <th class="text-muted border-0 py-2 font-weight-normal d-none d-md-block">
                                                Details</th>
                                            <th class="text-muted border-0 py-2 font-weight-normal">Address</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for p in allocated_properties %}
                                        <tr>
                                            <td class="border-0">
                                                <img src="{{ p.listing.image.url }}" class="rounded img-responsive mr-2"
                                                    height="30" width="30" alt="">
                                                {{ p.listing.title }}
                                            </td>
                                            <td class="border-0 pt-3 text-muted d-none d-md-block">
                                                {{p.listing.bedrooms}} Rooms, {{p.listing.bathrooms}} Baths, {{p.listing.garage}} Garage, {{p.listing.area}}m<sup>2</sup>
                                            </td>
                                            <td class="border-0 pt-3 text-muted">
                                                <span class=" d-none d-md-inline">{{ p.listing.get_address }} </span>
                                            </td>
                                                                          
                                        </tr>
                                        
                                        {% empty %}

                                        <tr>
                                            <br>
                                            <td>  You've not been allocated any properties yet </td>
                                        </tr>

                                        {% endfor %}                               
                                    </tbody>
                                </table>
                            </div> <!-- end table-responsive-->
                        </div> <!-- end card-body-->
                    </div>
                </div>
            </div>

            
            
        </main>
    </div>



    <!-- Graphs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <script>
        // This demo uses the Chartjs javascript library
        // Simple yet flexible JavaScript charting for designers & developers
        // Webite: https://www.chartjs.org
        // CDN: https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js

        const percent = {{ payment_progress }};
        const color = '#01713c';
        const canvas = 'chartCanvas';
        const container = 'chartContainer';

        const percentValue = percent; // Sets the single percentage value
        const colorGreen = color, // Sets the chart color
            animationTime = '1400'; // Sets speed/duration of the animation

        const chartCanvas = document.getElementById(canvas), // Sets canvas element by ID
            chartContainer = document.getElementById(container), // Sets container element ID
            divElement = document.createElement('div'), // Create element to hold and show percentage value in the center on the chart
            domString = '<div class="chart__value"><p>' + percentValue + '%</p></div>'; // String holding markup for above created element

        // Create a new Chart object
        const doughnutChart = new Chart(chartCanvas, {
            type: 'doughnut', // Set the chart to be a doughnut chart type
            data: {
                datasets: [
                    {
                        data: [percentValue, 100 - percentValue], // Set the value shown in the chart as a percentage (out of 100)
                        backgroundColor: ['#FC8210'], // The background color of the filled chart
                        borderWidth: 0 // Width of border around the chart
                    }
                ]
            },
            options: {
                cutoutPercentage: 84, // The percentage of the middle cut out of the chart
                responsive: true, // Set the chart to not be responsive
                tooltips: {
                    enabled: false // Hide tooltips
                },
                rotation: 135
            }
        });

        Chart.defaults.global.animation.duration = animationTime; // Set the animation duration

        divElement.innerHTML = domString; // Parse the HTML set in the domString to the innerHTML of the divElement
        chartContainer.appendChild(divElement.firstChild); // Append the divElement within the chartContainer as it's child

    </script>

</body>

{% endblock content %}