blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name='blog_index'),
    path('<int:pk>/<slug:slug>/', views.blog_single, name='blog_single'),
    path('tag/<slug:tag_slug>/', views.blog_index, name='posts_by_tag'),
    path('search/', views.blog_search, name='blog_search'),

]

listings/urls.py
from django.urls import path
from listings import views

app_name = 'listings'


urlpatterns = [
    path('', views.index, name='index'),
    path('listings/', views.listings, name='listings'),
    path('listing/<int:id>/<slug:slug>/', views.single_listing, name='single_listing'),
    path('search/', views.search, name='search'),
    path('add-wishlist/', views.add_wishlist, name='add_wishlist'),
    path('sort/<str:by>', views.sort, name='sort'),
    path('dashboard/properties/marketer/', views.dashboard_marketer_properties, name='dashboard_marketer_properties'),
    path('dashboard/properties/client/', views.dashboard_client_properties, name='dashboard_client_properties'),
    path('dashboard/wishlist/', views.dashboard_wishlist, name='dashboard_wishlist'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('faqs/', views.faqs, name='faqs'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
    path('', include('users.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('blog/', include('blog.urls')),
    path('transactions/', include('transactions.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] 
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from transactions import views

app_name = 'transactions'

urlpatterns = [
    path("confirm-purchase/<int:listing_id>/", views.confirm_purchase, name="confirm_purchase"),
    path("checkout/<int:trans_id>/", views.checkout, name="checkout"),
    path("checkout-confirmation/<int:trans_id>/", views.checkout_confirmation, name="checkout_confirmation"),
    path("payment-success/<int:listing_id>/", views.payment_success, name="payment_success"),
    path("invoice/<int:listing_id>/", views.invoice, name="invoice"),
]

users/urls.py
from django.urls import path

from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('s/<str:refer_code>/', views.signup, name='signup'),
    path('activate-email/<str:uid>/<str:token>/', views.activate_email, name='activate_email'),
    path('resend-activation-email/', views.resend_activation_email, name='resend_activation_email'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/client/', views.client_dashboard, name='client_dashboard'),
    path('dashboard/marketer/', views.marketer_dashboard, name='marketer_dashboard'),
    path('dashboard/profile/', views.profile, name='profile'),
    path('dashboard/profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
]

transactions/models.py
from django.db import models

from listings.models import Listing
from users.models import User
from utils.tools import generate_unique_id


class Transaction(models.Model):
    TRANSFER, DEPOSIT  = 0, 1
    PAYMENT_CHOICES = (
        (TRANSFER, 'Bank Transfer'),
        (DEPOSIT, 'Bank Deposit'),  
    )
    ZENITH, FIDELITY, ACCESS = 0, 1, 2
    BANK_CHOICES = (
        (ZENITH, 'Zenith Bank'),
        (FIDELITY, 'Fidelity Bank'),
        (ACCESS, 'Access Bank'), 
    )
    SUBMITTED, PROCESSING, RECEIVED, COMPLETED, ALLOCATED = 0, 1, 2, 4, 5
    STATUS_CHOICES = (
        (SUBMITTED, 'Submitted'),
        (PROCESSING, 'Processing'),
        (RECEIVED, 'Received'),
        (COMPLETED, 'Complete'),
        (ALLOCATED, 'Allocated'),
    )
    file = models.FileField(upload_to='transactions', verbose_name='Teller Image/File', null=True, blank=True)
    teller_name = models.CharField(max_length=50, null=True, blank=True)
    bank_reference = models.CharField(max_length=50, unique=True, null=True, blank=True)
    bank = models.PositiveSmallIntegerField(choices=BANK_CHOICES, null=True, blank=True)
    listing = models.ForeignKey(Listing, on_delete=models.DO_NOTHING)
    payment_type = models.PositiveSmallIntegerField(choices=PAYMENT_CHOICES, null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, null=True, blank=True)
    reference = models.CharField(max_length=50, null=True, blank=True)
    amount_to_pay = models.DecimalField(
		default=0.00,
		decimal_places=2,
		max_digits=12,
	)
    amount_paid = models.DecimalField(
		default=0.00,
		decimal_places=2,
		max_digits=12,
	)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    # discount_code = models.ForeignKey(DiscountCode, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.reference = generate_unique_id(Listing, 'reference', len=10)

        super().save(*args, **kwargs)



# class DiscountCode(models.Model):
#     code = models.CharField(max_length=6, unique=True)
#     amount = models.PositiveIntegerField()
#     start_date = models.DateField()
#     end_date = models.DateField()

transactions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from decimal import Decimal
from django.db.models import Sum

from listings.models import Listing
from transactions.models import Transaction #, DiscountCode



@login_required
def confirm_purchase(request, listing_id):

    listing = get_object_or_404(Listing, id=listing_id) 

    if request.method == "POST":
        amount_to_pay = request.POST.get('amount_to_pay')
        # discount_code = request.POST.get('discount_code')

        # discount = DiscountCode.objects.filter(code=discount_code)
        # if discount.exists():
        #     amount_to_pay -= discount.amounnt
            
            


           
        trans = Transaction.objects.create(listing=listing,
                                        user=request.user,
                                        amount_to_pay=amount_to_pay, 
                                        status=Transaction.SUBMITTED)
        return redirect(reverse('transactions:checkout', kwargs={'trans_id': trans.id}))


    context = {"listing": listing}
    return render(request, 'transactions/confirm_purchase.html', context)


@login_required
def checkout(request, trans_id):

    if request.method == 'POST':
        payment_type = request.POST.get('payment_type', 0)

        trans = Transaction.objects.get(id=trans_id)
        trans.payment_type = payment_type
        trans.save()
        return redirect(reverse('transactions:checkout_confirmation', args=[trans_id]))

    return render(request, 'transactions/checkout.html', {'trans_id': trans_id} )



@login_required
def checkout_confirmation(request, trans_id):

    if request.method == 'POST':
        bank = request.POST.get('bank')
        teller_name = request.POST.get('teller_name')
        amount_paid = request.POST.get('amount_paid')
        file = request.FILES.get('file')
        bank_reference = request.POST.get('amount_paid')

        if file:
            fs = FileSystemStorage()
            fs.save(file.name, file)

        trans = Transaction.objects.get(id=trans_id)

        # incase of a subsequent or additional payment
        if trans.bank or trans.teller_name or trans.amount_paid:
            Transaction.objects.create(
                                        listing = trans.listing,
                                        user = request.user,
                                        amount_to_pay = trans.amount_to_pay, 
                                        status = Transaction.PROCESSING,
                                        bank = bank,
                                        teller_name = teller_name,
                                        amount_paid = amount_paid,
                                        file=file
                                        )
        else:  
            # first payment made                              
            trans.bank = bank
            trans.teller_name = teller_name
            trans.bank_reference = bank_reference
            trans.status = Transaction.PROCESSING
            trans.file = file
            trans.amount_paid += Decimal(amount_paid)
            trans.save()
        return redirect(reverse('transactions:payment_success', args=[trans.listing.id]))

    return render(request, 'transactions/checkout_confirmation.html', {'trans_id': trans_id})


@login_required
def payment_success(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    return render(request, 'transactions/payment_success.html', {'listing': listing})


def invoice(request, listing_id):

    trans = Transaction.objects.filter(listing_id=listing_id, user=request.user, status__in=[Transaction.RECEIVED, Transaction.COMPLETED, Transaction.ALLOCATED])
    last_trans = trans.last()
    listing = last_trans.listing
    sum_paid = trans.aggregate(Sum('amount_paid'))['amount_paid__sum']
    balance = listing.price - sum_paid
    context = {
        "listing": listing,
        "sum_paid": sum_paid,
        "last_trans": last_trans,
        "balance": balance,
    }
    return render(request, 'transactions/invoice.html', context)

templates/transactions/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
<style>
 body {
    background-image: none;
  }
  .card {
    background-color: #F9FEFF !important;
    border: 1px solid #E0E0F4;
  }
  .card-header {background-color: #EBF5F7;}
  .card-text {
    font-size: 12px !important;

  }
  .card-title {
    font-size: 16px !important;
    color: #003333;
  }
  form {
    font-size: 14px;
  }
  .main-button {background-color: #FC8210 !important;}
  .second-button {
    color: #FC8210 !important;
    border: 1px solid #FC8210 !important;
    background-color: #fff !important;
  }
</style>
{% endblock extrastyle %}

{% block title %} Checkout - {% endblock title %}




{% block content %}

{% include 'partials/navbar.html' %}



    <div class="my-1 my-md-4 py-5"></div>



    <div class="text-center mb-5">
        <p class="h1"><strong>Checkout</strong> </p>
        <p class="h3 col-12 col-md-7 mx-auto text-secondary">Choose a bank account to pay or transfer to, pay via transfer or deposit.  Confirm or edit your personal details and proceed to enter your transaction details upon payment.</p>
    </div>

    <div class="container">
      <div class="row mx-auto col-md-9">
        <div class="col border rounded text-center p-4 p-md-5 mr-0 mr-md-3 ">
          <p class="h4 pb-3">Our Bank Accounts </p>
          <div class="card mb-3">
            <div class="card-header">United Bank for Africa</div>
            <div class="card-body py-2">
              <p class="card-text mb-0">Account Name</p>
              <h5 class="card-title">Westan Investments & Innovations Limited</h5>
              <p class="card-text mb-0">Account No</p>
              <h5 class="card-title">1023661243</h5>
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-header">GT Bank</div>
            <div class="card-body py-2">
              <p class="card-text mb-0">Account Name</p>
              <h5 class="card-title">Westan Investments & Innovations Limited</h5>
              <p class="card-text mb-0">Account No</p>
              <h5 class="card-title">xxxxxxxxx</h5>
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-header">Access Bank plc</div>
            <div class="card-body py-2">
              <p class="card-text mb-0">Account Name</p>
              <h5 class="card-title">Westan Investments & Innovations Limited</h5>
              <p class="card-text mb-0">Account No</p>
              <h5 class="card-title">xxxxxxxxx</h5>
            </div>
          </div>
        </div>
        <div class="col border rounded ml-0 ml-md-3  p-4 p-md-5">
          <p class="h4 pb-3 text-center font-weight-bold">Checkout Form</p>
          <form action="{% url 'transactions:checkout'  trans_id %}" method='POST' class="needs-validation mb-0" novalidate>
            {% csrf_token %}
              {% comment %} <input type="hidden" class="form-control" value='{{trans_id}}' name='trans_id'> {% endcomment %}
              <div class="mb-3">
                <label for="validationTooltip02">Email address</label>
                <input type='email' class="form-control" value='{{user.email}}' name="email" id="validationTooltip02" disabled>
              </div>
              <div class="mb-3">
                <label for="validationTooltip03">Phone number</label>
                <input type="number" class="form-control" value='{{user.phone}}' name='name' id="validationTooltip03" disabled>
              </div>
              <div class="mb-3">
                <label for="validationTooltip04">Payment method</label>
                <select name='pyament_type' class="custom-select" id="validationTooltip04" required>
                  <option selected disabled value="">Choose...</option>
                  <option value="0">Bank Transfer</option>
                  <option value="1">Bank Deposit</option>
                </select>
              </div>
              <button class="main-button btn btn-primary w-100 mb-3 border-0" type="submit">Confirm Payment</button>
              <a href="{% url 'users:dashboard' %}" class="second-button btn btn-primary w-100 mb-0" type="submit">Confirm Payment Later</a>
          </form>
        </div>
      </div>
    </div>
      

    
      <div class="py-5"></div>

      
      <script>
      // JavaScript for disabling form submissions if there are invalid fields
        (function() {
            'use strict';
            window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
                }, false);
            });
            }, false);
        })();
      </script>

  {% endblock content %}

templates/transactions/confirm_purchase.html
{% extends 'base.html' %}

{% load static humanize %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
<style>
  body {
    background-image: none;
  }
  .container > .card {
      border-radius: 10px !important;
  }
  .property-detail {
      background-color: hsla(190, 43%, 95%, 0.9) !important;
      color: #003333;
      border-radius: 10px;
      border: 1px solid hsla(240, 10%, 50%, 0.7) !important;
  }
  .card-body .card-text,
  .card-footer {
      color: #5A6F6F;
  }
  .card-footer {
      font-size: 14px !important;
  }
  form {
    font-size: 14px;
    color: #003333;
  }
  .col-form-label { color: #73738D;}
  form button {background-color: #FC8210 !important;}
</style>
{% endblock extrastyle %}

{% block title %} Confirm Purchase - {% endblock title %}



{% block content %}

{% include 'partials/navbar.html' %}


    <div class="my-1 my-md-4 py-5"></div>


    <div class="text-center mb-5">
        <p class="h1"><strong>Confirm Purchase</strong> </p>
        <p class="h3 col-12 col-md-7 mx-auto text-secondary">Your property is few clicks away. Click on checkout and proceed to payment page.</p>
    </div>

    <div class="container">
        <div class="card shadow-sm mb-3">
            <div class="row no-gutters rounded overflow-hidden">
              <div class="col-md-8 overflow-hidden">
                <img src="{{ listing.image.url }}" class="card-img rounded-0 h-100" alt="Listing image">
                <div class="card-img-overlay px-4 px-md-5 d-flex flex-col-reverse">
                    <div class="property-detail rounded bg-secondary w-100 mt-auto border">
                        <h5 class="price rounded text-white float-right bg-secondary px-3 py-2 mt-4 mr-4 d-none d-md-block"><span>&#8358;</span> {{listing.price|intcomma}}</h5>
                        <div class="card-body ml-3">
                            <h4 class="card-title p-0 mb-0"><strong>{{ listing.title }}</strong></h4>
                            <p class="card-text text-secondary d-none d-md-block">
                                <img src="{% static 'img/location.svg' %}" alt="">
                                {{ listing.get_address }}
                            </p>
                          </div>
                        
                        <div class="card-footer d-none d-md-block">
                            <div class="mb-0 ">
                                <span class='ml-3'>{{ listing.bedrooms }} Rooms</span>
                                <span class='ml-3'>{{ listing.bathrooms }} Baths</span>
                                <span class='ml-3'>{{ listing.garage }} Garage</span>
                                <span class='ml-3'>{{ listing.area }}m<sup>2</sup></span>
                            </div>
                          </div>
                    </div>
                    
                  </div>
              </div>
              <div class="col-md-4">
                <div class="card-body p-4 p-md-5">
                    <h4 class="card-title font-weight-bold text-center mb-4">Amount to Pay Now</h4>
                    <form action="{% url 'transactions:confirm_purchase' listing.id %}" method="POST">
                    {% csrf_token %}
                        <div class="form-group row">
                            <label for="price" class="col-6 col-form-label">Price </label>
                            <h5 class="col-6 pb-1"> <span>&#8358;</span> {{listing.price|intcomma}}</h5>
                        </div>
                        <div class="form-group row">
                          <label for="discount-code" class="col-6 col-form-label">Discount Code</label>
                          <div class="col-6">
                            <input type="text" name="discount_code" class="form-control" id="discount-code" >
                          </div>
                        </div>
                        <div class="form-group row">
                            <label for="price" class="col-6 col-form-label">Amount Payable</label>
                            <div class="col-6">
                              <h5 class="card-title"><span>&#8358;</span> {{listing.price|intcomma}}</h5>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="amount-pay-now" class="col-6 col-form-label">Amount to Pay Now</label>
                            <div class="col-6">
                              <input type="number" name="amount_to_pay" class="form-control" id="amount-pay-now" required>
                            </div>
                          </div>
                        <button type="submit" class="btn btn-primary w-100 border-0">Checkout</button>
                        
                      </form>
                </div>
              </div>
            </div>
          </div>
    </div>
 
      <div class="py-5"></div>

      
  

{% endblock content %}

templates/transactions/invoice.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

{% endblock extrastyle %}

{% block title %} Property Invoice {% endblock title %}




{% block content %}


   
<body class="container-fluid">
    <div class="header">
        <!-- Navbar -->
       {% include 'partials/dashboard_navbar.html' %}
    </div>
    <div class="row">
        <!-- Sidebar -->

        {% include 'partials/dashboard_sidebar.html' %}

        <!-- Sidebar ends -->

        <!-- Main content -->
        <main role="main" class="col-md h-100 overflow-aut p-4">
            <div class="py-5 d-block d-md-none"></div>

            <!-- Heading and Filters -->
            <div class="row mb-4 d-flex align-items-end d-print-none">
                <h3 class="col font-weight-bold text-center text-md-left mb-4 mb-md-0">Property Invoice</h3>
                <div class="col-auto d-md-flex align-items-center">
                    <a href="{% url 'listings:dashboard_client_properties' %}" class="col-auto btn orange border-orange bg-white px-4 ml-3">Back to Properties</a>
                    <a href="javascript:window.print()" class="col-auto btn bg-orange text-white px-4 ml-3">Print</a>
                </div>

            </div>


            <div class="row mb-5">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-2 p-md-5">

                            <!-- Invoice Logo-->
                            <div class="clearfix position-relative">
                                <div class="float-left position-absolute mb-3 d-none d-md-block">
                                    <img src="{% static 'img/logo.svg' %}" alt="" height="40">
                                </div>
                                <div class="text-center pt-3 pt-md-0">
                                    <h2 class="m-0 pb-2 d-print-none font-weight-bold">Westan Investments & Innovations Limited (RC 1714571)</h2>
                                    <address>80, Aina street, Ojodu-Berger, Lagos state.
                                        <br>
                                        <span>Email: westanhomesng@gmail.com</span>
                                    </address>
                                </div>
                            </div>

                            <!-- Invoice Detail-->
                            <div class="row mt-4 mt-md-5">
                                <div class="col-sm-4">
                                    <h6>Client</h6>
                                    <address>
                                        {{user.full_name}} <br>
                                        {{user.address}} <br>
                                        <span> {{user.phone}} </span>
                                    </address>
                                </div> <!-- end col-->

                                <div class="col-sm-4 order-sm-0 text-center pt-auto">
                                    <h4>Sales Reciept</h4>
                                </div> <!-- end col-->

                                <div class="col-sm-4">
                                    <div class="float-sm-right">
                                        <p class="font-13 mb-0">Transaction reference</p>
                                        <p class="h4">{{ last_trans.reference }}</p>
                                        <p class="font-13">{{last_trans.created_at}} </p>
                                    </div>
                                </div><!-- end col -->
                            </div>    
                            <!-- end row -->        

                            <div class="row">
                                <div class="col-12">
                                    <div class="table-responsive">
                                        <table class="table mt-4">
                                            <thead>
                                            <tr><th>Item</th>
                                                <th>Description</th>
                                                <th>Price</th>
                                                <th>Last Payment</th>
                                                <th class="text-right">Total Payments</th>
                                            </tr></thead>
                                            <tbody>
                                            <tr>
                                                <td>1</td>
                                                <td>
                                                    {{listing.title}} <br/>
                                                    {{ listing.get_address }}
                                                </td>
                                                <td> <span>&#8358;</span>{{listing.price|intcomma}} </td>
                                                <td><span>&#8358;</span>{{last_trans.amount_paid|intcomma}} </td>
                                                <td class="text-right"><span>&#8358;</span>{{sum_paid|intcomma}} </td>
                                            </tr>
                                         
                                            </tbody>
                                        </table>
                                    </div> <!-- end table-responsive-->
                                </div> <!-- end col -->
                            </div>
                            <!-- end row -->

                            <div class="row">
                                <div class="col-sm-6">
                                </div> <!-- end col -->
                                <div class="col-sm-6">
                                    <div class="float-right mt-3 mt-sm-0">
                                        <p><b>Balance: </b> <span class="float-right"> <span>&#8358;</span> {{balance|intcomma}}</span></p>
                                        <p><b>Paid:</b> <span class="float-right ml-1"> <span>&#8358;</span>{{last_trans.amount_paid|intcomma}}</span></p>
                                        {% comment %} <h3><span>&#8358;</span>{{sum_paid|intcomma}}</h3> {% endcomment %}
                                    </div>
                                    <div class="clearfix"></div>
                                </div> <!-- end col -->
                            </div>
                            <!-- end row-->

                            <!-- end buttons -->

                        </div> <!-- end card-body-->
                    </div> <!-- end card -->
                </div> <!-- end col-->
            </div>
            <!-- end row -->




            
            
        </main>
    </div>

</body>

  {% endblock content %}

templates/transactions/payment_success.html
{% extends 'base.html' %}

{% load static humanize %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
<style>
  body {
    background-image: none;
  }
  /* .card {
    background-color: #F9FEFF !important;
    border: 1px solid #E0E0F4;
  }
  .card-header {background-color: #EBF5F7;}
  .card-text {
    font-size: 12px !important;

  }
  .card-title {
    font-size: 16px !important;
    color: #003333;
  } */
  .container .card {
      border-radius: 10px !important;
  }
  .property-detail {
      background-color: hsla(190, 43%, 95%, 0.9) !important;
      color: #003333;
      /* opacity: 0.5; */
      border-radius: 10px;
      border: 1px solid hsla(240, 10%, 50%, 0.7) !important;
  }
  .card-body .card-text,
  .card-footer {
      color: #5A6F6F;
  }
  .card-footer {
      font-size: 14px !important;
  }
  .btn-dash {
    background-color: #FC8210 !important;
    color: #ffffff;
  }
</style>

{% endblock extrastyle %}

{% block title %} CPayment Successful - {% endblock title %}



{% block content %}

{% include 'partials/navbar.html' %}


  

    <div class="my-1 my-md-4 py-5"></div>



    <div class="text-center mb-5">
        <p class="h1"><strong>Payment Details Received!</strong> </p>
        <p class="h3 col-12 col-md-7 mx-auto text-secondary">Dear client, kindly exercise some patience as our account department is trying to confirm and effect your payment for this property. You will get a notification as soon as your payment has been confirmed.</p>
    </div>

    <div class="container">
      <div class="col-md-9 mx-auto">
        <div class="card shadow-sm mb-3 overflow-hidden">
            <img src="{{ listing.image.url }}" class="card-img rounded-0 h-100" alt="Listing Image">
                <div class="card-img-overlay px-3 px-md-5 d-flex flex-col-reverse">
                    <div class="property-detail rounded bg-secondary w-100 mt-auto border">
                        <h5 class="price rounded text-white float-right bg-secondary px-3 py-2 mt-4 mr-4 d-none d-md-block"><span>&#8358;</span>{{listing.price|intcomma}}</h5>
                        <div class="card-body ml-3">
                            <h4 class="card-title p-0 mb-0"><strong>{{ listing.title }}</strong></h4>
                            <p class="card-text text-secondary d-none d-md-block">
                                <img src="{% static 'img/location.svg' %}" alt="">
                                    {{ listing.get_address }} 
                            </p>
                        </div>
                        
                        <div class="card-footer d-none d-md-block">
                            <div class="mb-0 ">
                              <span class='ml-3'>{{ listing.bedrooms }} Rooms</span>
                              <span class='ml-3'>{{ listing.bathrooms }} Baths</span>
                              <span class='ml-3'>{{ listing.garage }} Garage</span>
                              <span class='ml-3'>{{ listing.area }}m<sup>2</sup></span>
                            </div>
                        </div>
                    </div>
                    
                </div>
          </div>
      </div>
      <div class="text-center">
        <a href="{% url 'users:dashboard' %}" type="submit" class="btn btn-dash px-5 border-0 mt-4">Go to Dashboard</a>
      </div>
      
    </div>

    

      <div class="py-5"></div>

      
  {% endblock content %}